version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./Gateway
    ports: 
      - "8000:8000"

  characters:
    container_name: characters
    restart: always
    build: ./Characters
    ports: 
      - "3001:3001" 

  films:
    container_name: films
    restart: always
    build: ./Films
    ports: 
      - "3002:3002" 

  planets:
    container_name: planets
    restart: always
    build: ./Planets
    ports: 
      - "3003:3003" 
      
  database:
    container_name: database
    restart: always
    build: ./Database
    ports: 
      - "3004:3004" 