FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3001

CMD [ "npm", "start" ]

# docker build -t database .
#   

# Whit NetWork
# docker run -dp 8004:8004 --network=star_wars --name=database database